import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
  //   variable: "--font-geist-sans",
  //   subsets: ["latin"],
  // });
  
  // const geistMono = Geist_Mono({
    //   variable: "--font-geist-mono",
    //   subsets: ["latin"],
    // });
    
    import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core';
    import '@mantine/core/styles.css';
    import "@/app/scss/global.scss";


import { theme } from '../theme';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
